import {
  JourneyMilestone,
  EducationItem,
  CertificationItem,
  ActivityItem,
} from "./types";

export const DEFAULT_MILESTONES: ReadonlyArray<JourneyMilestone> = [
  {
    role: "IT Specialist",
    company: "Allied Care Experts (ACE) Medical Center – Butuan Inc.",
    startDate: "2026-07",
    endDate: "present",
    period: "July 2026 - Present",
    year: "July 2026 - Present",
    title: "IT Specialist",
    description:
      "Administer hospital-wide IT systems, HIS, databases, and network infrastructure, while leading the full-stack engineering of the enterprise ACEMC HRIS platform.",
    location: "Butuan, PH (On-site)",
    tags: [
      "Next.js 16",
      "React 19",
      "TypeScript",
      "Tailwind CSS",
      "Shadcn/ui",
      "Supabase",
      "PostgreSQL 16",
      "Proxmox VE",
      "Docker",
      "Coolify",
      "Nginx",
      "Kong",
      "Realtime",
    ],
    highlights: [
      "Administer IT systems, databases, and network infrastructure supporting hospital-wide operations, including the hospital information system (HIS); resolve hardware, network, and system issues independently to maintain uptime across clinical and administrative departments, and document configurations to support onboarding of future IT staff.",
      "Lead development of the ACEMC HRIS, an enterprise HR and payroll platform (Next.js 16, React 19, TypeScript, self-hosted Supabase/PostgreSQL 16) replacing spreadsheet-based operations for hospital staff, doctors, and nurses, including an Employee Self-Service portal for timecards, leave and overtime requests, and e-payslips, with real-time notifications powered by Supabase Realtime.",
      "Designed the PostgreSQL database schema and planned the on-premises hospital deployment on Proxmox VE using Docker, Coolify, Nginx, and Kong, hosting the platform on the hospital's own infrastructure.",
      "Engineered an in-memory batch payroll engine covering Philippine statutory contributions and tax (SSS, PhilHealth, Pag-IBIG, BIR) that replaced sequential per-employee database queries with bulk parallel pre-fetching, computing payroll for hundreds of employees in sub-second time.",
      "Built a biometric punch pipeline that compiles Daily Time Records and calculates night differentials, tardiness, and overtime across rotating 24/7 shifts; added a Compensatory Time Off ledger using PostgreSQL triggers and a cafeteria POS reconciliation with fuzzy name matching for payroll deductions.",
      "Secured employee PII, compensation data, and audit trails across four role tiers (Employee, Department Head, HR Staff, HR Admin) using PostgreSQL Row-Level Security and Supabase SSR session middleware, supporting Data Privacy Act compliance.",
    ],
    metrics: [
      { label: "Payroll Engine", value: "<1s" },
      { label: "Hospital Staff", value: "400+" },
      { label: "Shift Coverage", value: "24/7" },
    ],
  },
  {
    role: "Software Developer (Contract)",
    company: "Zionix Consultancy Services Company",
    startDate: "2026-06",
    endDate: "2026-08",
    period: "June 2026 – August 2026",
    year: "June 2026 – August 2026",
    title: "Software Developer (Contract)",
    description:
      "Sole developer and project manager for Phase 1 of a production real estate management information system (MIS).",
    location: "Remote",
    tags: [
      "Next.js",
      "TypeScript",
      "Supabase",
      "Tailwind CSS",
      "Shadcn/ui",
      "PostgreSQL",
      "RPC Functions",
    ],
    highlights: [
      "Architect and develop a real estate management information system (MIS) as sole developer and project manager, using Next.js App Router, TypeScript, Supabase, Tailwind CSS, and shadcn/ui — delivering Phase 1 (Core Sales & Inventory Tracker) to production.",
      "Implement database-level safeguards including Row-Level Security policies, pessimistic locking via custom RPC functions, and full audit logging, ensuring data integrity across concurrent multi-user transactions.",
      "Conduct full-codebase architecture reviews, producing prioritized technical recommendations (error monitoring, JWT custom claims, indexing strategy, server-side pagination) that reduced technical debt ahead of subsequent phases.",
    ],
    metrics: [
      { label: "Property Listings", value: "60+" },
      { label: "Project Phase", value: "Phase 1" },
      { label: "Property Buyers", value: "40+" },
    ],
  },
  {
    role: "Web Developer & UI Designer (Self-employed)",
    company: "Freelance",
    startDate: "2024-10",
    endDate: "2026-08",
    period: "October 2024 – August 2026",
    year: "October 2024 – August 2026",
    title: "Web Developer & UI Designer (Self-employed)",
    description:
      "Designed, developed, and deployed custom web applications and business websites for small and medium-sized business clients.",
    location: "Remote",
    tags: [
      "Next.js",
      "React.js",
      "Vue.js",
      "Supabase",
      "PostgreSQL",
      "Tailwind CSS",
      "Shadcn/ui",
      "Vuetify",
      "Laravel",
      "Django",
      "MySQL",
      "SQLite",
      "PHP",
      "Python",
      "JavaScript",
      "TypeScript",
      "HTML",
      "CSS",
      "Postman",
      "Figma",
      "Git",
      "Github",
    ],
    highlights: [
      "Design, develop, and deploy custom web applications and business websites for additional small and medium-sized business clients as an independent developer, using modern frameworks including Next.js, React, Vue.js, and Supabase.",
      "Create user interface designs and responsive layouts with Tailwind CSS, shadcn/ui, and Vuetify, translating client requirements into intuitive, user-friendly experiences.",
      "Implement secure authentication and real-time data management with Supabase and PostgreSQL, and manage each project end to end, from requirements gathering to production deployment.",
    ],
    metrics: [
      { label: "Custom Apps", value: "Full-Stack" },
      { label: "Frameworks", value: "Next/React/Vue" },
      { label: "Delivery", value: "End-to-End" },
    ],
  },
  {
    role: "Full-Stack Developer (Intern)",
    company: "Office of Curriculum and Instruction Development",
    startDate: "2025-06",
    endDate: "2025-09",
    period: "June 2025 – September 2025",
    year: "June 2025 – September 2025",
    title: "Full-Stack Developer (Intern)",
    description:
      "Engineered backend architecture, PostgreSQL database logic, and React administrative dashboard for an employee database management system.",
    location: "Butuan, PH (On-site Intern)",
    tags: ["Laravel", "PostgreSQL", "React.js", "Tailwind CSS", "RESTful APIs"],
    highlights: [
      "Engineered backend architecture and database logic for a custom employee database management system using Laravel and PostgreSQL, reducing average query time by ~35% through optimized schema design and indexing.",
      "Developed and integrated secure RESTful APIs, enabling reliable data exchange across 5+ core system modules with zero reported downtime — directly supporting business process automation.",
      "Designed and implemented a responsive administrative dashboard using React.js and Tailwind CSS, streamlining data management and improving end-user accessibility.",
      "Produced technical documentation throughout the SDLC and delivered the full system on schedule within a 3-month timeline — from requirements gathering to production deployment.",
    ],
    metrics: [
      { label: "Query Speedup", value: "35%" },
      { label: "Core Modules", value: "5+" },
      { label: "Project Timeline", value: "3 Mos" },
    ],
  },
] as const;

export const EDUCATION_ITEMS: readonly EducationItem[] = [
  {
    degree: "B.S. in Information Technology",
    school: "Caraga State University - Main Campus",
    period: "August 2021 - June 2026",
    gpa: "2.00",
    courses: [
      "Web Development",
      "Mobile Application Development",
      "Networking",
      "Database Systems",
      "Software Engineering",
      "Fundamentals of Programming",
      "Data Structures and Algorithms",
      "Systems Integration and Architecture",
      "Information Assurance and Security",
      "Human-Computer Interaction",
      "AI and Intelligent Systems",
    ],
    highlights: [
      "Awarded Vice President's Lister for attaining a 1.38 GPA during the 1st Semester of Academic Year 2025-2026.",
      "Developed an AI-powered multilingual profanity detection Chrome extension for real-time web content filtering as a thesis project.",
      "Represented the Caraga Region at the national level after winning back-to-back Regional Championships at Hack4Gov (2024 & 2025), a cybersecurity Capture The Flag competition, with team CarSU CyberNinja.",
      "Secured 3rd place nationally at the DOST Level Up Game Dev Challenge 2024 building 'Sinawali Showdown' frontend with Vue 3.",
    ],
  },

  {
    degree: "Senior High School",
    school: "ACLC College Butuan",
    period: "2018 - 2020",
    gpa: "2.25",
    courses: ["Computer System Servicing (CSS) NCII"],
    highlights: [
      "Acquired technical skills in computer hardware and software troubleshooting and maintenance.",
      "Completed hands-on training and assessments for practical application of technical knowledge.",
    ],
  },
];

export const CERTIFICATION_ITEMS: readonly CertificationItem[] = [
  {
    title: "AWS Certified Solutions Architect",
    issuer: "Amazon Web Services",
    date: "2025",
    credId: "AWS-ASA-99212",
    verifyKey: "0x8f2d9a3b00fe41",
    skills: [
      "VPC Architecture",
      "Serverless (Lambda)",
      "ECS/EKS Containerization",
      "Cloud Security",
    ],
  },
  {
    title: "Meta Advanced React Developer",
    issuer: "Meta (Coursera)",
    date: "2024",
    credId: "META-ARD-88341",
    verifyKey: "0x4c2b9a78fd1230",
    skills: [
      "Custom Hooks",
      "Concurrent Mode",
      "React Performance Profiling",
      "State Managers",
    ],
  },
  {
    title: "Vercel Next.js Developer Certification",
    issuer: "Vercel",
    date: "2025",
    credId: "VRC-NJS-77429",
    verifyKey: "0x9e107d3fa20bb1",
    skills: [
      "App Router Architecture",
      "Server Actions",
      "PPR Configurations",
      "Edge Middleware",
    ],
  },
];

export const ACTIVITY_ITEMS: readonly ActivityItem[] = [
  {
    title: "CarSU CyberNinja",
    role: "Member (Cybersecurity Team)",
    period: "2023 – 2025",
    metrics: [
      { label: "Hack4Gov", value: "2x Champ" },
      { label: "Standing", value: "Regional" },
      { label: "Qualifier", value: "National" },
    ],
    tags: [
      "Ethical Hacking",
      "Vulnerability Assessment",
      "CTF",
      "Web Exploitation",
      "Network Analysis",
      "Cryptography",
      "Steganography",
      "Digital Forensics",
    ],
    highlights: [
      "Applied hands-on ethical hacking and vulnerability assessment techniques in Capture the Flag (CTF) competitions representing Caraga State University, covering web exploitation, network analysis, cryptography, steganography, and digital forensics.",
      "Earned back-to-back Regional Championships at Hack4Gov 2024 and 2025, qualifying to represent Caraga State University and the Caraga Region at the national level.",
    ],
  },
  {
    title: "CSU Game Developers Club",
    role: "Frontend Developer",
    period: "2024",
    metrics: [
      { label: "DOST Level Up", value: "3rd Place" },
      { label: "Platform", value: "In-Browser" },
      { label: "Game Engine", value: "Custom Vue" },
    ],
    tags: [
      "Vue 3",
      "Pinia",
      "JavaScript",
      "Tailwind CSS",
      "Turn-Based Logic",
      "Game Dev",
    ],
    highlights: [
      "Developed the frontend of Sinawali Showdown with the CSU Game Developers Club at Caraga State University, a Filipino cultural turn-based card game built without a game engine using Vue 3 and Pinia state management, delivering a polished and responsive in-browser experience.",
      "Achieved 3rd Place at DOST Level Up Game Dev Challenge 2024 (National) representing Caraga State University.",
    ],
  },
];
