allowBuilds:
  sharp: true
  unrs-resolver: true
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
minimumReleaseAgeExclude:
  - postcss@8.5.10
  - hono@4.12.25
overrides:
  postcss@<8.5.10: ^8.5.10
